#! /bin/sh


case "$1" in
	start)
	echo "Starting init script for aesdchar Loading"
	start-stop-daemon -S -n init -a /bin/aesdchar_load
	;;

	stop)
	echo "Removing aesdchar driver"
	start-stop-daemon -K -n aesdchar_load
	start-stop-daemon -S -n init -a /bin/aesdchar_unload
	;;

	*)
	echo "Usage: $0 {start|stop}"
		exit 1
esac

exit 0